### ISSUE TITLE
[bug] not all args set in values.yaml forwarded correctly

### ISSUE THREAD

**Issue by twelvemountains** [F5Networks/charts#27]
#### Description
The helm chart for the f5-bigip-ctrl does not pass all additional args to the controller as desired, since it wraps them in additional quotes:
https://github.com/F5Networks/charts/blob/master/src/stable/f5-bigip-ctlr/templates/f5-bigip-ctlr-deploy.yaml#L63
This results in using the default values for example for use-node-internal argument, making the controller always export internal IPs to the f5 device, even though configured otherwise in the values.yaml.
Changing the args forwarding in f5-bigip-ctrl-deploy.yaml as follows solves the problem:
```
.
.
.
61    {{- range $key, $value := .Values.args }}
62            - --{{ $key | replace "_" "-"}}={{ $value }}
63            {{- end }}
.
.
.
```
#### Kubernetes Version
1.14.1

#### Controller Version
1.9.1

#### BIG-IP Version
v13

#### Helm / Tiller Version
v2.14.2

**Comment by trinaths** [comment]
Closed. The existing conventions work well.
