### ISSUE TITLE
Migrate extensions/v1beta1 deploy to apps/v1

### ISSUE THREAD

**Issue by mitchellmaler** [F5Networks/charts#29]
#### Description
Kubernetes 1.16 removes the extensions/v1beta1 api https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/. All templates using the deprecated APIs should be migrated to the stable API.

#### Kubernetes Version
N/A

#### Controller Version
N/A

#### BIG-IP Version
N/A

#### Helm / Tiller Version
N/A

#### Diagnostic Information
N/A

**Comment by trinaths** [comment]
This issue is resolved. https://github.com/F5Networks/charts/blob/master/src/stable/f5-bigip-ctlr/templates/_helpers.tpl#L14 
Closing this issue.
