### ISSUE TITLE
The f5-bigip-ctlr helm chart lists version as optional but there's no default value (thus its not optional)

### ISSUE THREAD

**Issue by bradley-baker** [F5Networks/charts#63]
The big-ip-ctlr helm chart readme lists the version as optional:

```
version	Optional	CIS Controller image tag	latest
```

However if you omit setting it the chart won't install with an error indicating invalid image name:

```
  Warning  InspectFailed  9m38s (x13 over 11m)  kubelet, d-cont-wkr1  Failed to apply default image tag "f5networks/k8s-bigip-ctlr:": couldn't parse image reference "f5networks/k8s-bigip-ctlr:": invalid reference format
  Warning  Failed         6m50s (x26 over 11m)  kubelet, d-cont-wkr1  Error: InvalidImageName
```

Setting the version in the helm chart does address the problem but the readme shouldn't say its optional and/or the default values.yml should be setting it to `latest`

**Comment by TJbredow** [comment]
Yeah, I had the same issue. I had to declare "latest". I created a pull request to add that logic. You can see the change in the helm chart templates there.
It didn't happen when running dockershim as my CRI, but it did with CRI-O.

**Comment by trinaths** [comment]
@bab5470  please follow installation instruction from https://clouddocs.f5.com/containers/latest/userguide/cis-helm.html#installing-cis-using-helm-charts
